spring.application.name=inventoryService
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/ecom_inventory
spring.datasource.username=postgres
spring.datasource.password=Rohan@1207
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true

eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8080/eureka/

