-- TRUNCATE TABLE category;
-- INSERT INTO category (name) VALUES ('Electronics');
-- INSERT INTO category (name) VALUES ('Clothing');
-- INSERT INTO category (name) VALUES ('Books');
-- INSERT INTO category (name) VALUES ('Home & Kitchen');
-- INSERT INTO category (name) VALUES ('Sports & Fitness');
-- INSERT INTO category (name) VALUES ('DIY Gadgets');