spring.application.name=eurekaServer
server.port=${SERVER_PORT:8080}
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=${EUREKA_SERVERR_URL:http://localhost:8080/eureka/}
eureka.instance.prefer-ip-address=true